const systemConfig = require('../../config/system');
const dashboardRoutes = require('./dashboard_route');
const dashboardApiRoutes = require('./api/dashboard_route');
const productsdRoutes = require('./products_route');
const productsApiRoutes = require('./api/products_route');
const importsRoutes = require('./imports_route');
const adjustmentsRoutes = require('./adjustments_route');
const importsApiRoutes = require('./api/imports_route');
const exportsRoutes = require('./exports_route');
const exportsApiRoutes = require('./api/exports_route');
const ordersRoutes = require('./orders_route');
const ordersApiRoutes = require('./api/orders_route');
const reviewsRoutes = require('./reviews_route');
const reviewsApiRoutes = require('./api/reviews_route');
const authRoutes = require('./auth_route');
const authApiRoutes = require('./api/auth_route');
const usersRoutes = require('./users_route');
const usersApiRoutes = require('./api/users_route');
const reportsRoutes = require('./reports_route');
const reportsApiRoutes = require('./api/reports_route');
const settingsApiRoutes = require('./api/settings_route');
const vouchersRoutes = require('./vouchers_route');
const vouchersApiRoutes = require('./api/vouchers_route');
const bannersRoutes = require('./banners_route');
const bannersApiRoutes = require('./api/banners_route');
const brandsApiRoutes = require('./api/brands_route');
const categoriesApiRoutes = require('./api/categories_route');
const homeSectionsRoutes = require('./home_sections_route');
const homeSectionsApiRoutes = require('./api/home_sections_route');
const flashSalesRoutes = require('./flash_sales_route');
const flashSalesApiRoutes = require('./api/flash_sales_route');
const lookbooksRoutes = require('./lookbooks_route');
const lookbooksApiRoutes = require('./api/lookbooks_route');
const brandsRoutes = require('./brands_route');
const categoriesRoutes = require('./categories_route');
const sizeGuidesRoutes = require('./size_guides_route');
const sizeGuidesApiRoutes = require('./api/size_guides_route');
const blogRoutes = require('./blog_route');
const blogApiRoutes = require('./api/blog_route');
const chatRoutes = require('./chat_route');
const chatApiRoutes = require('./api/chat_route');
const { requireAdmin } = require('../../middlewares/auth');
module.exports =(app)=>{
    const PATH_ADMIN = systemConfig.prefigAdmin;
    // Admin auth pages (no requireAdmin)
    app.use(PATH_ADMIN, authRoutes);
    app.use(PATH_ADMIN + '/api/auth', authApiRoutes);

    // Protect all remaining admin routes
    app.use(PATH_ADMIN, requireAdmin);
    app.use(PATH_ADMIN + '/', dashboardRoutes);
    app.use(PATH_ADMIN + '/dashboard', dashboardRoutes);  
    app.use(PATH_ADMIN + '/ai-assistant', dashboardRoutes);
    app.use(PATH_ADMIN + '/api/dashboard', dashboardApiRoutes);
    app.use(PATH_ADMIN + '/products', productsdRoutes); 
    app.use(PATH_ADMIN + '/api/products', productsApiRoutes);
    app.use(PATH_ADMIN + '/imports', importsRoutes);
    app.use(PATH_ADMIN + '/adjustments', adjustmentsRoutes);
    app.use(PATH_ADMIN + '/api/imports', importsApiRoutes);
    app.use(PATH_ADMIN + '/exports', exportsRoutes);
    app.use(PATH_ADMIN + '/api/exports', exportsApiRoutes);
    app.use(PATH_ADMIN + '/orders', ordersRoutes);
    app.use(PATH_ADMIN + '/api/orders', ordersApiRoutes);
    app.use(PATH_ADMIN + '/reviews', reviewsRoutes);
    app.use(PATH_ADMIN + '/api/reviews', reviewsApiRoutes);
    app.use(PATH_ADMIN + '/users', usersRoutes);
    app.use(PATH_ADMIN + '/api/users', usersApiRoutes);
    app.use(PATH_ADMIN + '/reports', reportsRoutes);
    app.use(PATH_ADMIN + '/api/reports', reportsApiRoutes);
    app.use(PATH_ADMIN + '/api/settings', settingsApiRoutes);
    app.use(PATH_ADMIN + '/vouchers', vouchersRoutes);
    app.use(PATH_ADMIN + '/api/vouchers', vouchersApiRoutes);
    app.use(PATH_ADMIN + '/banners', bannersRoutes);
    app.use(PATH_ADMIN + '/api/banners', bannersApiRoutes);
    app.use(PATH_ADMIN + '/home-sections', homeSectionsRoutes);
    app.use(PATH_ADMIN + '/api/home-sections', homeSectionsApiRoutes);
    app.get(PATH_ADMIN + '/settings/home', (req, res) => res.redirect(PATH_ADMIN + '/home-sections'));
    app.use(PATH_ADMIN + '/flash-sales', flashSalesRoutes);
    app.use(PATH_ADMIN + '/api/flash-sales', flashSalesApiRoutes);
    app.use(PATH_ADMIN + '/lookbooks', lookbooksRoutes);
    app.use(PATH_ADMIN + '/lookbook', lookbooksRoutes);
    app.use(PATH_ADMIN + '/api/lookbooks', lookbooksApiRoutes);
    app.use(PATH_ADMIN + '/brands', brandsRoutes);
    app.use(PATH_ADMIN + '/api/brands', brandsApiRoutes);
    app.use(PATH_ADMIN + '/categories', categoriesRoutes);
    app.use(PATH_ADMIN + '/category', categoriesRoutes);
    app.use(PATH_ADMIN + '/api/categories', categoriesApiRoutes);
    app.use(PATH_ADMIN + '/size-guides', sizeGuidesRoutes);
    app.use(PATH_ADMIN + '/api/size-guides', sizeGuidesApiRoutes);
    app.use(PATH_ADMIN + '/blog', blogRoutes);
    app.use(PATH_ADMIN + '/api/blog', blogApiRoutes);
    app.use(PATH_ADMIN + '/chats', chatRoutes);
    app.use(PATH_ADMIN + '/api/chats', chatApiRoutes);
}